### ISSUE TITLE
isActive not working on v8.latest

### ISSUE THREAD

**Issue by BarryFogarty** [AaronSadlerUK/Our.Umbraco.UmbNav#11]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

8.16

### Bug summary

isActive property is always false

### Steps to reproduce

Install the package and add some items to the menu.  Go to one of those items.  inSpect the isActive property

### Expected result / actual result

The isActive property of the current menu item should be true when you visit its URL.

**Comment by AaronSadlerUK** [comment]
I have reworked this to use the IPublishedContent item rather than the stored key from the backoffice.

Let me know if it fixes it for you
