### ISSUE TITLE
Allow labels to show child nodes of a page

### ISSUE THREAD

**Issue by tzbarkan** [AaronSadlerUK/Our.Umbraco.UmbNav#15]
There are situations where we want a label with dynamic children. But the only way to do that is with a link. It would be helpful if there were a way to have a label that could show child nodes of a specific page.

**Comment by AaronSadlerUK** [comment]
I'll need to have a think on this one, so it may not make v1.0.0-rc.11

If you have something in mind, please do work on it and submit a PR 😇

**Comment by tzbarkan** [comment]
Understood. Thinking about it, maybe a checkbox in advanced configuration for links would do the trick: "Display as label"...

**Comment by AaronSadlerUK** [comment]
I think that idea will work, the issue with the flow is a label is stored as a text item, and as such has no "children" as it's not a content item.

I will add the checkbox for display as label, this will simple toggle the itemtype to be label which in return will null the relevant parts on the c# side.
