### ISSUE TITLE
Make toggles consistent on Navigation - UmbNav data type

### ISSUE THREAD

**Issue by tzbarkan** [AaronSadlerUK/Our.Umbraco.UmbNav#17]
Going down the list of toggleable features in the data type, it can get a little confusing as to which toggles disable something and which ones enable something. It would be great if all toggles behaved consistently, instead of having some toggles Allow something and others Hide something.

**Comment by AaronSadlerUK** [comment]
I agree, I will see what I can do with these to make them more consistent :)

**Comment by AaronSadlerUK** [comment]
Ok so I've had a play with this.

It would be a pretty crucial change, as the configuration items are set in a c# class rather than in the model, and modifying the value doesn't work.

Instead I have re-ordered the items so that they are more consistent.

**Comment by tzbarkan** [comment]
I can imagine it would be a big effort. Thanks for looking into it.
