### ISSUE TITLE
Render Tree structure

### ISSUE THREAD

**Issue by Sven883** [AaronSadlerUK/Our.Umbraco.UmbNav#18]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

v8.15.1

### Bug summary

Hello ! 

I'm testing your package for eventual use in one of our future projects.
I've added some nodes to the tree and I'm trying to render them using following code: 

`@foreach (var item in Model.Content.Website().Menu)
{
    @item.GetLinkHtml(Model.CurrentCulture.Name)
}`

Unfortunately this is only rendering the rootnodes without the children.

Any info on how to render the whole tree? Thanks!

### Steps to reproduce

Use this code to render tree: 

`@foreach (var item in Model.Content.Website().Menu)
{
    @item.GetLinkHtml(Model.CurrentCulture.Name)
}`

### Expected result / actual result

Rendering the full tree.

**Comment by AaronSadlerUK** [comment]
You would need to do a recursive loop.

For example from the demo site a 2 level navigation:

https://github.com/AaronSadlerUK/Our.Umbraco.UmbNav/blob/e9c19155ed7e05140a6b3eed43989066bef24951/TestSite/Views/Partials/Navigation/TopNavigation.cshtml#L10-L64

**Comment by Sven883** [comment]
Hey @AaronSadlerUK 
Thanks for the quick response!

Ok, I will add this in the code. I thought it would automatically get the children in the 'GetLinkHtml' extension method.

Thanks!

**Comment by AaronSadlerUK** [comment]
Unfortunately not, as every one renders their menu's different, and so I was unable to come up with a re-usable method
