### ISSUE TITLE
Missing Umbraco.sdf for the testsite?

### ISSUE THREAD

**Issue by mistyn8** [AaronSadlerUK/Our.Umbraco.UmbNav#2]
;-)
And presumably some backoffice credentials?

**Comment by AaronSadlerUK** [comment]
Clear the database connection string in the web.config for the TestSite reinstall, and then go to Settings -> uSync and Import 👍

**Comment by AaronSadlerUK** [comment]
I have now added uSync to the V9 test site

**Comment by mistyn8** [comment]
Should have spotted uSync. doh.
