### ISSUE TITLE
RC10 dependency on re-release Examine 2.0.0-beta2 is incompatible with Umbraco 8.16.0

### ISSUE THREAD

**Issue by tzbarkan** [AaronSadlerUK/Our.Umbraco.UmbNav#20]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

8.16.0

### Bug summary

RC10 requires Examine 2.0.0-beta2, but Umbraco 8.16.0 requires Examine < 2.0.0. 

I'm not sure about future versions of Umbraco 8.*, but it would be a deal breaker for us to upgrade Umbraco to support a pre-release Examine package. Given the amount of work you've put in to support Umbraco 8, it's a shame to have one dependency make your whole package incompatible.

### Steps to reproduce

Try to update to RC10 pre-release of UmbNav

**Comment by AaronSadlerUK** [comment]
I am unable to reproduce this.
I have upgraded the website to 8.16.0

I have then upgraded UmbNav with the Dependency behaviour set to **Lowest** and it installs fine with no warning, and it does not upgrade the installed dependency from 1.2.1 in this case.

![image](https://user-images.githubusercontent.com/9937803/132371846-dc442c57-f3fa-4097-87a1-261daf5345dd.png)
