### ISSUE TITLE
Install-Package Our.Umbraco.UmbNav.Web not working

### ISSUE THREAD

**Issue by ziyadsv** [AaronSadlerUK/Our.Umbraco.UmbNav#27]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

v8.15.2

### Bug summary

Install-Package Our.Umbraco.UmbNav.Web

### Steps to reproduce

can find the file on nuget  Our.Umbraco.UmbNav.Web

**Comment by AaronSadlerUK** [comment]
Please make sure you have cleared your Nuget cache.

I was able to install from nuget fine today.

**Comment by ziyadsv** [comment]
I found it . we need to click the Include prerelease checkbox .
