### ISSUE TITLE
V9 RC11 red outline and greyed out

### ISSUE THREAD

**Issue by nzdev** [AaronSadlerUK/Our.Umbraco.UmbNav#28]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

V9RC3

### Bug summary

The navigation ui is greyed out and has a red box around it

![image](https://user-images.githubusercontent.com/834725/133955774-c418d36f-d6da-4c74-8203-f960844562fb.png)

### Steps to reproduce

Install UmbNav. Use with existing MegaNavV8 document (new umbnav config).

### Expected result / actual result

No red box, not greyed out.

**Comment by AaronSadlerUK** [comment]
Do these nodes have the umbracoNaviHide property, and if so is it set to true?

This should only happen when you have that property and set it to true
