### ISSUE TITLE
UmbNav is not showing on the front end

### ISSUE THREAD

**Issue by ziyadsv** [AaronSadlerUK/Our.Umbraco.UmbNav#29]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

8.16.0

### Bug summary

After we update the cms to latest stable version 8.16.0. Umbnav is not taking on the front end .its shows blank

### Steps to reproduce

install or update the umbraco version

**Comment by ziyadsv** [comment]
any solutions?

**Comment by AaronSadlerUK** [comment]
@ziyadsv I've not had chance to look yet.

Anything in the error logs relating to UmbNav?

**Comment by ziyadsv** [comment]
![umbnav](https://user-images.githubusercontent.com/7956063/134996593-69958bb7-b46d-4cb4-8e03-d343425d56ed.png)


Log level is info and message is Manifest has changed, app pool is restarting.
I have menu content but it showing the array is zero. {UmbNav.Core.Models.UmbNavitem[0]}

**Comment by AaronSadlerUK** [comment]
@ziyadsv I think I've found the issue, I'm just working on the fix now =]

**Comment by ziyadsv** [comment]
still have some issues. I created a new project and tried to install from the umbraco package its showing me the following error 
![image](https://user-images.githubusercontent.com/7956063/135269623-6df4a4ad-5ad4-4419-9e51-7d914734a696.png)
