### ISSUE TITLE
Not able to install package from umbraco package

### ISSUE THREAD

**Issue by ziyadsv** [AaronSadlerUK/Our.Umbraco.UmbNav#31]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

8.16.0

### Bug summary

Umbraco not make me install the umbnav package

### Steps to reproduce

I created a new project on umbraco 8.16.0 and tried to install from the umbraco package its showing me the following error 

![image](https://user-images.githubusercontent.com/7956063/135270595-d1fb95f5-2a60-4ae9-add1-951a246739fc.png)

**Comment by AaronSadlerUK** [comment]
I have re-uploaded the package as 1.0.2.

Please note I am no longer supporting the backoffice package installer, and only supporting and pushing future releases to Nuget to align with the Umbraco V9 process.
