### ISSUE TITLE
External Links not working

### ISSUE THREAD

**Issue by ja0b** [AaronSadlerUK/Our.Umbraco.UmbNav#56]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

8.17.1

### Bug summary

When using external links the UmbNavItem doesn't have the link value. The Content property comes back as null and there is not other property reflecting the link value although the ItemType is set correctly to Link.

### Steps to reproduce

Add an external link and try to render it.

**Comment by AaronSadlerUK** [comment]
I'll try and replicate this and get back to you soon
