### ISSUE TITLE
Image on Child is not working

### ISSUE THREAD

**Issue by ziyadsv** [AaronSadlerUK/Our.Umbraco.UmbNav#6]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

v8.15.2

### Bug summary

parent image is showing but the image on the child is not working.

### Steps to reproduce

``@foreach (var item in nav.UmbNav)
        {            
                <h3>@item.Title</h3>
                @if (item.Children.Count() != 0)
                {
                    <ul>
                        @foreach (var child in item.Children)
                        {                            
                            <li>
                                @if (child.Image != null)
                                {
                                    <img alt="@child.Image.Name" src="@child.Image">
                                }                                
                                <a href="@child.Url()" target="@child.Target" rel="@child.Noopener @child.Noreferrer">@child.Title</a>
                            </li>
                        }
                    </ul>
                }
        }``

### Expected result / actual result

The result of child item image is  null.

**Comment by AaronSadlerUK** [comment]
I will look into this and issue a patch soon ☺

**Comment by AaronSadlerUK** [comment]
Ok so I've taken a look at this, and I am unable to replicate with the latest rc (1.0.0-rc.9)

Can you try clicking edit on the affected menu item, re-select the picture and then Save and Publish to see if it resolves it.

I have updated the navbar testing code to show what I've used to test here:
https://github.com/AaronSadlerUK/Our.Umbraco.UmbNav/blob/46cef503da96d757bda922cfcb51e33d6d589241/TestSite/Views/Partials/Navigation/TopNavigation.cshtml

**Comment by ziyadsv** [comment]
Will you please check with the latest umbraco version 8.17.0-rc . Am using
three UmbNav on one page. but sometimes it's not showing the image. after i
uninstall and reinstall the UmbNav package it didn't show me entire menu
