### ISSUE TITLE
Include Child Nodes toggle doesn't stick

### ISSUE THREAD

**Issue by amirkhan81** [AaronSadlerUK/Our.Umbraco.UmbNav#65]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

8.17.0

### Bug summary

In the content section, the Include Child Nodes Toggle doesn't stick after clicking submit to close the overlay, this is regardless of whether or not there are child nodes.

### Steps to reproduce

Add UmbNav data type to document type, making sure the Include Children option is enabled < select a node > check the include child nodes box > press submit > press edit > note that the box is unchecked. The same thing happens if you submit > save and publish > edit.

**Comment by AaronSadlerUK** [comment]
@amirkhan81 This should be fixed in 1.1.2
