### ISSUE TITLE
Url not available on Link UmbNavItem

### ISSUE THREAD

**Issue by nzdev** [AaronSadlerUK/Our.Umbraco.UmbNav#68]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

9.4.3

### Bug summary

Url not available on Link UmbNavItem. When using the Link navigation item type the url is not available.

### Steps to reproduce

Set up a doc with umbnav
Set up a Link item type with a url and no anchor set
Retrieve the UmbNavItem from the Published Property
Url is not available

### Expected result / actual result

Url is available.

**Comment by AaronSadlerUK** [comment]
@nzdev Can you confirm which version of UmbNav you are using?

**Comment by onionstar** [comment]
@nzdev, I was having a similar problem but I had not added @using UmbNav.Core.Extensions into my view, as soon as I did item.Url() worked like a charm

**Comment by nzdev** [comment]
Thanks @onionstar ! Looks like that should work. I'll give it a go tomorrow.

**Comment by AaronSadlerUK** [comment]
@nzdev Was this solved?

**Comment by nzdev** [comment]
I believe so. Thanks.
