### ISSUE TITLE
After the update UmbNav doesn't work

### ISSUE THREAD

**Issue by desily** [AaronSadlerUK/Our.Umbraco.UmbNav#69]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

10.3.2

### Bug summary

I made the latest update of "UmbNav" to version 2.0.3 and in the "Content Section" I no longer see the items I had uploaded. I cannot add or delete entries.
The naming of my menu items has changed to a generic "item".
For example: "legislation" has become "item 1".
In the frontend the entries are displayed correctly
![umbnav](https://user-images.githubusercontent.com/52072628/203281218-9d0a36fc-9de2-4b67-96a8-53b254ea3c05.PNG)

### Steps to reproduce

Create a menu and then update Umbnav to the version 2.0.3

### Expected result / actual result

be able to edit, add, view items as before the upgrade

**Comment by AaronSadlerUK** [comment]
There are no differences between 2.0.2 and 2.0.3 other than a tag being added for the new Umbraco Marketplace.

What version did you upgrade from?

Have you tried clearing the temp folder and your browser caches?

Are there any errors in the browser console?

Can you please give me a step-by-step way to replicate this.

Thanks!

**Comment by desily** [comment]
Thank you for your answer.
There are no errors in the browser console.
I cleared the cache but no change.
Before I had installed version 2.0.2.
It occurs to me now that I've also switched to .Net 7.0. I tried to go back to version 2.0.2 and .Net 6.0, but the anomaly remained.
The strangest thing is that I no longer see the "edit" and "delete" buttons.
Thanx

**Comment by AaronSadlerUK** [comment]
I haven't tested it with NET 7.0 or Umbraco 11 (yet)

As you can see here there is only 1 change between the 2 versions:

https://github.com/AaronSadlerUK/Our.Umbraco.UmbNav/compare/2.0.2...2.0.3

Are there any errors in the log?

I would need something to go on to be able to replicate this and investigate, if you're on Slack we could discuss this privately if you wanted to share any screenshots / code?

**Comment by desily** [comment]
Thanx.
I contact you by Slack

**Comment by AaronSadlerUK** [comment]
This has been fixed in version 2.0.4 which is now available on NuGet

https://www.nuget.org/packages/Our.Umbraco.UmbNav.Web/2.0.4
