### ISSUE TITLE
trying to add multiple sub menu items to top Nav

### ISSUE THREAD

**Issue by alienrock** [AaronSadlerUK/Our.Umbraco.UmbNav#71]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

11.1.0

### Bug summary

I am trying to create multiple sub menu items under main navigation and unable to see the items after they are added on the screen.

### Steps to reproduce

this can be reproduced by trying to add multi level sub menu items under main nav

**Comment by AaronSadlerUK** [comment]
You need to write the foreach look for each set of child items.

They can be found in Children

See #70 for more about this discussion and example code
