### ISSUE TITLE
Retrieve value from IVirtualPageController (?) does not work

### ISSUE THREAD

**Issue by arenisland** [AaronSadlerUK/Our.Umbraco.UmbNav#72]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

10.2.1

### Bug summary

When using a route the GetValue from a UmbNav property returns null

### Specifics

I'm not 100% sure this is related to IVirtualPageController but it's working for "normal" pages

I have a route setup like this
```
u.EndpointRouteBuilder.MapControllerRoute(
"Category view",
"/category/{shortname}",
new { Controller = "Category", Action = "Category" });
```

And the controller looks something like this
```
public class CategoryController : UmbracoPageController, IVirtualPageController
{
   public IPublishedContent? FindContent(ActionExecutingContext actionExecutingContext)
    {
        if (_umbracoContextAccessor.TryGetUmbracoContext(out var umbracoContext))
        {
            var categoryRoot = umbracoContext.Content.GetById(1083); // todo: hämta listnamn
            if (categoryRoot != null)
            {
                return categoryRoot;
            }
        }

        return null;
    } 

    public IActionResult Category(string shortname)
    {
        // retrieve data from db etc
        var viewmodel = new MyViewModel();
        return View(viewmodel);
    }
}
```

The view inherits a layout that calls a TopMenu component
`@(await Component.InvokeAsync("TopNavigation", new { selected = Model.Selected }))`

And that component looks like this
```
[ViewComponent(Name = "TopNavigation")]
public class TopNavigationViewComponent : ViewComponent
{
    private readonly INavigationService navigationService;

    public TopNavigationViewComponent(INavigationService navigationService)
    {
        this.navigationService = navigationService;
    }

    public IViewComponentResult Invoke(int selected)
    {
        var model = new TopNavigationViewModel()
        {
            Items = this.navigationService.GetTopNavigation(),
        };
        return View(model);
    }

}
```

The NavigationService
```
public class NavigationService : INavigationService
{
    private readonly UmbracoHelper umbracoHelper;
    private readonly ISiteSettings siteSettings;

    public NavigationService(UmbracoHelper umbracoHelper, ISiteSettings siteSettings)
    {
        this.umbracoHelper = umbracoHelper;
        this.siteSettings = siteSettings;
    }

    public List<IPublishedContent> GetSubNavigation(int currentId)
    {
        var currentPage = this.umbracoHelper.Content(currentId);
        var parentOrSelf = currentPage.AncestorOrSelf(2);
        return parentOrSelf.Children?.ToList();
    }

    public IEnumerable<UmbNavItem> GetTopNavigation()
    {
        var menu = this.siteSettings.Menu;
        return menu;
    }
}
```

The siteSettings
```
public class SiteSettings : ISiteSettings
{
    private readonly UmbracoHelper umbracoHelper;
    private readonly IUmbracoContextFactory umbracoContextFactory;
    private readonly IContentService contentService;

    public SiteSettings(UmbracoHelper umbracoHelper, IUmbracoContextFactory umbracoContextFactory, IContentService contentService)
    {
        this.umbracoHelper = umbracoHelper;
        this.umbracoContextFactory = umbracoContextFactory;
        this.contentService = contentService;
    }

    private IPublishedContent home => this.umbracoHelper.ContentAtXPath($"//{ContentTypeAlias.Home}")?.FirstOrDefault();
    private IPublishedContent settings  => this.umbracoHelper.ContentAtXPath($"//{ContentTypeAlias.SiteSettings}")?.FirstOrDefault();

    public string SiteName => this.home.Name;

    public IEnumerable<UmbNavItem> Menu => this.settings.GetProperty(PropertyAlias.HeaderMenu).GetValue() as IEnumerable<UmbNavItem>;

}
```

When NOT using the route the GetValue works fine and I get an IEnumerable<UmbNavItem>
But when using the route i will get this (immediate window)
```
this.settings.GetProperty(PropertyAlias.HeaderMenu).GetValue() as IEnumerable<UmbNavItem>
Count = 0
    Current: null
    Results View: Expanding the Results View will enumerate the IEnumerable
```
If I add a watch to this.settings.GetProperty(PropertyAlias.HeaderMenu) I get that the _sourceValue is set 
`[{"udi":"umb://document/0dea73210cd349c492846538f436bb33","key":"0dea7321-0cd3-49c4-9284-6538f436bb33","name":"Om oss","description":"/om-oss/","title":"Om oss","url":"/om-oss/","children":[],"icon":"icon-umb-content color-blue","published":true,"naviHide":false,"culture":null,"itemType":"link","id":1075,"collapsed":true},{"udi":"umb://document/bdec7357fd824e36bb112bf0a490614b","key":"bdec7357-fd82-4e36-bb11-2bf0a490614b","name":"Min sida","description":"/min-sida/","url":"/min-sida/","children":[],"icon":"icon-umb-content color-blue","published":true,"naviHide":false,"culture":null,"itemType":"link","id":1080,"collapsed":true}]`

but _sourceValues are null.

I created another text propery and I can retrieve that without problem so I figured that there might be something with UmbNav

If I compare the watch data when calling from route compared to without, I can't find anything different of the two.

### Steps to reproduce

I add screenshots of the watch data, if that is useful.

Watch for call WITHOUT route
![image](https://user-images.githubusercontent.com/106648139/218723042-8f4310b8-c5d0-4dde-8c8f-c3dd67f3d453.png)

Watch for call WITH route
![image](https://user-images.githubusercontent.com/106648139/218722445-a8e7c887-adef-4928-804c-b257683e91d9.png)

### Expected result / actual result

Expected to retrieve a value from GetValue, but instead got null result

**Comment by AaronSadlerUK** [comment]
This is not something I have ever tested, or been required to use.

I added the ability to query the `IPublishedContent` quite a while ago, so on the umbnav item there is a property called Content 
This is the `IPublishedContent` item for the menu item selected, you should be able to do [item.Content.Value()](url) on that.

**Comment by arenisland** [comment]
Hi, thanks for response.

The problem is that I don't get the umbnav item when quering from routing.

I have a settings node that handles the menu. 
The settings node is found and I can get other properties from it. But when I try to retrieve the UmbNav property from it, it resolves as null. 

so when I do this.settings.GetProperty("myMenuProperty").GetValue() as IEnumerable<UmbNavItem> I get null
but this.settings.GetProperty("testtext").GetValue() as string I get the value of the text.

**Comment by AaronSadlerUK** [comment]
I'll be honest I've never queried for it that way.

I either create a service which collects the menu and I inject that into the view, the service uses the Umbraco context and collects the menu like this:

```
_siteSettings = rootContent.FirstOrDefault(x => x.IsDocumentType("siteSettings")) as SiteSettings ?? throw new InvalidOperationException("The Site Settings node needs to have been created before we can use this service");
```

I then use an interface and register the service as Transient, then in the view I can do something like:

```
@inject ISiteService SiteService

var siteSettings = SiteService.GetSiteSettings();
var umbNav = siteSettings.Value<IEnumerable<UmbNavItem>>("umbNav");

```

Otherwise if it's on the home node I do this:

```
var site = Model.Root();
var umbNav = site.Value<IEnumerable<UmbNavItem>>("umbNav");
```

I can't see of a reason to use GetProperty and GetValue to do it.

**Comment by arenisland** [comment]
Ok. Did some quick test and in the NavigationService I inject umbracoHelper

1074 is the id of the settings node. 

```
var test = umbracoHelper.Content(1074);
var hasValue = test.HasValue(PropertyAlias.HeaderMenu);
var umbNav = test.Value<IEnumerable<UmbNavItem>>("myMenu");
var param = test.Value<string>("test");
```

When I access a normal published page I get the value in both umbNav and param. But when I access the routing and hit the custom controller umbNav is null but param have value. hasValue is also true in both cases.

So somehow the UmbNavItem is empty all of a sudden?

**Comment by AaronSadlerUK** [comment]
The menu is build using a service which uses the Umbraco Context.

https://github.com/AaronSadlerUK/Our.Umbraco.UmbNav/blob/develop/src/UmbNav.Core/Services/UmbNavMenuBuilderService.cs#L39

This seems like an edge case, which requires knowledge of your site and the way it's been built to debug.

My suggestion would be to remove the NuGet package clone down the repo and add the .Api, .Core and .Web projects as project dependencies.

You will then be able to see what's going on in the UmbNavMenuBuilderService

**Comment by arenisland** [comment]
Again, thanks for pointing me in the right direction. I will look into it

**Comment by arenisland** [comment]
Think I found the reason on line 41-42

```
var currentPublishedContent = umbracoContext.PublishedRequest.PublishedContent;
currentPublishedContentKey = currentPublishedContent.Key;
```

Since my route isn't a published content node these lines will throw an exception. This is (only) used to set the active flag, so if there can be a check if umbracoContext.PublishedRequest.PublishedContent is null before retrieving the Key I guess things will work. If Key is left as Guid.Empty the menu will be returned with no post flagged as active.

Not sure if you want to add it to your solution to support custom routes, but that should be all there is to it. 

To explain more what my route is doing is that I have a route setup to intercept /product/{name}
And that route hits a controller to retrieve this info from an external database. 
It's then pointed to a view to render a custom ViewModel

**Comment by AaronSadlerUK** [comment]
Hmmmm it's a tricky one, as that it mainly used for the active class on the menu item.

If you can think of a way to make that work both ways that would be better!

A PR would be greatly appreciated if you manage that, I'm not sure at this point how to replicate otherwise.

Do you think you could create an example in one of the TestSites included in the repo so I can debug and test?

**Comment by arenisland** [comment]
I see if I get the time for an example in test, prob not, but maybe. Have a big load of work right now, but don't we all :)

If the code would be changed to this then both cases would work, right? It wouldn't break anything
```
var currentPublishedContent = umbracoContext.PublishedRequest.PublishedContent;
if(currentPublishedContent != null) {
   currentPublishedContentKey = currentPublishedContent.Key;
}
```
If it finds the published content it will mark it as active, otherwise it will compare it to Guid.Empty all the time and never hit and marking nothing as active.

**Comment by AaronSadlerUK** [comment]
Yeah sure it makes sense, I just need to make sure it doesn't break anything to a test would be great to ensure that

**Comment by AaronSadlerUK** [comment]
I'll add the null check and release an update shortly

**Comment by AaronSadlerUK** [comment]
You can grab 2.0.6 here:
https://www.nuget.org/packages/Our.Umbraco.UmbNav.Web/2.0.6
