### ISSUE TITLE
Label item type does not render when at the top level

### ISSUE THREAD

**Issue by BarryFogarty** [AaronSadlerUK/Our.Umbraco.UmbNav#73]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

Umbraco version 11.1.0

### Bug summary

If a label item is created as the top level, this does not appear in the model of the view.  If a label item is created as a child item of a link, it is contained in the model no problem

### Steps to reproduce

Add a label item to the top level
Add a label item as a child item to a link

### Expected result / actual result

Both label items should apper in the view model `IEnumerable<UmbNavItem>`
Only the nested item actually appears.

**Comment by AaronSadlerUK** [comment]
Can you provide an example or your code generating the menu so I can debug.

I've used Labels on a few V10 sites recently with no issues

**Comment by BarryFogarty** [comment]
Hey Aaron - This is v11 with .Net 7

My view looks like this

```
@inherits UmbracoViewPage<IEnumerable<UmbNavItem>>

@using UmbNav.Core.Extensions
@using UmbNav.Core.Models

@foreach (var link in Model)
{
...
}
```

If I debug into the `foreach` loop, label items do not appear in the model when they are at the top level

**Comment by AaronSadlerUK** [comment]
@BarryFogarty I am unable to replicate this, I have tried using both the taghelper and typing it out, both times the label renders at top level:

![image](https://user-images.githubusercontent.com/9937803/220588010-0b8d4477-82f1-4f01-8203-89b5e0752b03.png)


```
@foreach (var item in umbNav)
{
    <umbnavitem menu-item="item" active-class="nav-link--active" class="nav-link"></umbnavitem>
}
```

```
@foreach (var item in umbNav)
{
    @if (item.ItemType == UmbNavItemType.Label)
    {
        <span class="nav-link">@item.Title</span>
    }
    else
    {
        <a class="nav-link" href="@item.Url()" target="@item.Target">@item.Title</a>
    }
}
```

Can you provide me the complete loop and code for your menu, as well as a screenshot of the settings used on the data type so I can investigate further.

**Comment by BarryFogarty** [comment]
Hi Aaron - thanks for looking and sorry for the delay in getting back - this is a side project.  FYI I cleared out the menu data and started again and it works as expected.  I believe the issue is when you turn a link into a label.  It displays correctly in the CMS but is not included in the output model.  Here is a snippet of the erroring menu data, in case you can repro that way.

`[{"id":1179,"udi":null,"key":"46823367-83ae-4915-85f5-dbd93eb29bac","name":"News","description":null,"url":null,"children":[{"udi":"umb://document/3302e2a0c2cd4d5c98778a1b79b101c2","key":"3302e2a0-c2cd-4d5c-9877-8a1b79b101c2","name":"Home","description":"/","url":"/","children":[],"icon":"icon-home color-black","published":true,"naviHide":false,"culture":null,"itemType":"link"}],"icon":"icon-tag","published":true,"naviHide":false,"culture":null,"itemType":"nolink","displayAsLabel":false,"title":"Label","target":null,"noopener":false,"noreferrer":false,"anchor":null,"includeChildNodes":false}]`

As this item has all the properties of a link, but `"itemType":"nolink"`, the problem must lie here somewhere.  Hope this helps :-)

**Comment by AaronSadlerUK** [comment]
Thanks for that @BarryFogarty I will take a look 👍

**Comment by AaronSadlerUK** [comment]
It wasn't quite as simple as adding `item.Key == Guid.Empty; ` I also needed to add a fallback so that if the title is empty it uses the name.

It will be released shortly

**Comment by AaronSadlerUK** [comment]
You can grab 2.0.6 here
