### ISSUE TITLE
When ItemType == Link, cannot get Url

### ISSUE THREAD

**Issue by AussieInSeattle** [AaronSadlerUK/Our.Umbraco.UmbNav#76]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

8.16.0

### Bug summary

Umbraco 8.16.0
UmbNav 1.1.4

Code below fails as .Url is set to internal .Url() also fails - when linking to umbraco content, .Content.Url() works - this is just an issue when the type is Link.

```
if (subNavItem.ItemType == UmbNav.Core.Enums.UmbNavItemType.Link)
{
  <a href="@subNavItem.Url">@subNavItem.Title</a>
}
```

### Specifics

Seems to be that this line is set to internal?
https://github.com/AaronSadlerUK/Our.Umbraco.UmbNav/blob/umbraco-v8-v9/src/UmbNav.Core/Models/UmbNavItem.cs#L67

### Steps to reproduce

see code above

**Comment by AaronSadlerUK** [comment]
Yes that's correct, you need to use the extension method

.Url()

**Comment by AussieInSeattle** [comment]
that fails also (this is for type=link, not type=content) - see screenshot - am I missing a using that would make .Url() work?

![image](https://user-images.githubusercontent.com/2397814/223226404-b025790a-5439-4c57-8dff-7fa7e523d3bb.png)

**Comment by AaronSadlerUK** [comment]
Hmmm .Url() is in the UmbNav.Core DLL

It's been a long time since I've touched V1, I think link is for external URLs, I'd need to get a V8 site up and running to debug

**Comment by AussieInSeattle** [comment]
**I think link is for external URLs**
Correct - this is only an issue for external url's - am assuming this is only coming up now as it's rare to have external url's in your top navigation where this package is likely mostly used?

**Comment by AaronSadlerUK** [comment]
Yeah I think that could be the case, I've done this and got it working in V10+ So I presume it's a bug specific to V8...

I'll do some digging...

Can you give me an example of the backoffice item, so I can be 100% sure I'm debugging it correctly

**Comment by AussieInSeattle** [comment]
When debugging I can see .Url (string) populated under Non-Public Properties - so I think it's a matter of making .Url public but only when type=link - not sure who you'd do that

**Comment by AaronSadlerUK** [comment]
That was made internal for a specific reason, it broke things with the multilingual which is why the extension method was brought in...  I will debug this and get back to you

**Comment by AussieInSeattle** [comment]
Example below - cut off the bottom so I didnt have to blur out my content tree
![image](https://user-images.githubusercontent.com/2397814/223228068-67d726eb-a38d-4ed6-b512-a8711c1dc4e5.png)

**Comment by AussieInSeattle** [comment]
> That was made internal for a specific reason, it broke things with the multilingual which is why the extension method was brought in... I will debug this and get back to you

thanks - let me know if you need more info

**Comment by AaronSadlerUK** [comment]
I've just run V8 and it works for me:
![image](https://user-images.githubusercontent.com/9937803/223229485-1d40e061-ed74-468a-883c-ae9c8c43ad55.png)
![image](https://user-images.githubusercontent.com/9937803/223229555-e23b37b7-457c-4a00-8924-c5c08c4f36d7.png)

These are the two usings:
```
@using UmbNav.Core.Extensions
@using UmbNav.Core.Models
```

Are you use the `Url()` you are using in your code is the UmbNav one?
Your error seems to say `PublishedContentExtensions.Url()` whereas the UmbNav one is `UmbNavItemExtensions.Url()`

**Comment by AaronSadlerUK** [comment]
Just to add the UmbNav extension does a null check here:
https://github.com/AaronSadlerUK/Our.Umbraco.UmbNav/blob/ac2e3a9a59e8c2c5c8a8274443dad912ad9c0b8f/src/UmbNav.Core/Extensions/UmbNavItemExtensions.cs#L125

and returns .Url if it is null here:
https://github.com/AaronSadlerUK/Our.Umbraco.UmbNav/blob/ac2e3a9a59e8c2c5c8a8274443dad912ad9c0b8f/src/UmbNav.Core/Extensions/UmbNavItemExtensions.cs#L151

**Comment by AussieInSeattle** [comment]
good catch - missing using statement - adding this to view fixed it:
`@using UmbNav.Core.Extensions`
Will buy you a beer at CG for your troubles :-)

**Comment by AaronSadlerUK** [comment]
Glad you got it working!
