### ISSUE TITLE
Non Content Link Url not accessiable in Views

### ISSUE THREAD

**Issue by jamescutts** [AaronSadlerUK/Our.Umbraco.UmbNav#78]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

 version 10.5.1 

### Bug summary

When adding a menu item that is not internal content e.g. Link to https://google.com this value is not accessible due to `UmbNavItem.Url` being an internal property, thereby giving no way to render these within views.

### Steps to reproduce

Example of configured menu item containing an external non-content link.

![image](https://github.com/AaronSadlerUK/Our.Umbraco.UmbNav/assets/1178375/6981ec24-bfa4-4a8b-b7eb-bba7f807c24d)

### Expected result / actual result

A property is accessible wit the url for a non content link allowing code similar to the following to render the link to an external url.

```
<a href="@(child.Content != null ? child.Content.Url() :  child.Url)" target="@child.Target">
    @child.Title
</a>
```

**Comment by AaronSadlerUK** [comment]
.Url it not used, is internal and depreciated.

.Url() (the method) works with both internal and external links.

You will need to check you have included the using statement in your view
