### ISSUE TITLE
What is the difference between versions?

### ISSUE THREAD

**Issue by Eaglef90** [AaronSadlerUK/Our.Umbraco.UmbNav#85]
In NuGet there are 3 packages, .Core .Web and .API.  I figure the API is just the API calls but what are the difference between core and web? Just trying to figure out which is best to install. Thanks

**Comment by AaronSadlerUK** [comment]
The .Web contains the other two as dependencies and the backoffice files (App_Plugins folder)

.Core is the classes, typically installed when using Models Builder

**Comment by Eaglef90** [comment]
I see, thanks for the clarification.
