### ISSUE TITLE
Upgrade to U14

### ISSUE THREAD

**Issue by rydigitaldev** [AaronSadlerUK/Our.Umbraco.UmbNav#92]
Any plans to upgrade this to work on the new backoffice in v14 ? 
Thanks!

**Comment by AaronSadlerUK** [comment]
No.

I only support LTS versions, and as I'm not a front-end developer I do no have the skills currently to migrate this... I will accept PRs though!

The next version will ve V17 hopefully (The next LTS)

**Comment by CarlSargunar** [comment]
Aw go-wan. Go wan. Go wan go wan go wan go wan go wan go wan go wan go wan

Bonus points if you get the reference ;-)

**Comment by rydigitaldev** [comment]
ok, thanks anyway! (i know its a hude amount of FE work!)
