### ISSUE TITLE
Umbraco V14+ support

### ISSUE THREAD

**Issue by tkjaergaard** [AaronSadlerUK/Our.Umbraco.UmbNav#93]
Hi 👋

We've been using this package on a lot of projects from v8 to v13.

Any thoughts of supporting Umbraco 14 or will the package be a < v13 only?

**Comment by AaronSadlerUK** [comment]
Hi @tkjaergaard 

It's being worked on
https://github.com/AaronSadlerUK/UmbNav-V14

But with a target of v17 (LTS)

All PRs and help are massively appreciated as I am not a frontend developer

**Comment by tkjaergaard** [comment]
@AaronSadlerUK Cool 🙂
